<<<<<<< HEAD
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3" # Pypy3 2.4.0
# command to install dependencies
install:
  - pip install .
# command to run tests
script: torrench "ubuntu 16.04"
=======
language: python3
>>>>>>> 33cd6862e349eb13f0eeaf91d289a6f288655dca
